// Predefined strategy templates
// Each strategy follows the same JSON structure as generated by Preview

import { PredefinedStrategyTemplate } from "../components/strategy/block-types";


export const predefinedStrategies: PredefinedStrategyTemplate[] = [
  {
    id: "1",
    name: "Buy the Dip!",
    description: "Buy ETH and BTC when price drops at least 1% in 24 hours",
    strategy: {
      strategyId: "0391b0b0-01d8-4843-960a-e045052d7096",
      strategyName: "Buy when price drops",
      symbols: ["BTC/USD", "ETH/USD"],
      executionOptions: {
        runIntervalMinutes: 60,
        maximumExecuteCount: 10,
        intervalBetweenExecutionsMinutes: 360,
        maximumOpenPositions: 1
      },
      rules: [
        {
          name: "Buy the Dip",
          conditions: [
            {
              index: 0,
              type: "decreased-by",
              indicator1: "Price",
              timeframe1: "24h",
              value: 1,
            },
          ],
          actions: [
            {
              index: 0,
              action: "BUY",
              options: {
                amount: 25,
                unit: "USD",
              },
            },
          ],
        },
      ],
    },
  },
  {
    id: "2",
    name: "Buy HIGH, Sell LOW",
    description: "The best trading strategy,trust me bro.",
    strategy: {
      strategyId: "c7807204-2132-43ef-a23c-76d8d557dc7f",
      strategyName: "Buy High sell low",
      symbols: [
        "BTC/USD",
        "DOGE/USD",
        "SOL/USD"
      ],
      executionOptions: {
        runIntervalMinutes: 10,
        maximumExecuteCount: 100,
        intervalBetweenExecutionsMinutes: 1,
        maximumOpenPositions: 10
      },
      rules: [
        {
          name: "Buy High",
          conditions: [
            {
              index: 0,
              type: "increased-by",
              indicator1: "Price",
              timeframe1: "4h",
              value: 5
            }
          ],
          actions: [
            {
              index: 0,
              action: "BUY",
              options: {
                amount: 100,
                unit: "%"
              }
            },
            {
              index: 1,
              action: "NOTIFY",
              options: {
                channel: "Email",
                message: "Sure its gona go up!"
              }
            }
          ]
        },
        {
          name: "Sell Low",
          conditions: [
            {
              index: 0,
              type: "decreased-by",
              indicator1: "Price",
              timeframe1: "4h",
              value: 5
            }
          ],
          actions: [
            {
              index: 0,
              action: "SELL",
              options: {
                amount: 100,
                unit: "%"
              }
            },
            {
              index: 1,
              action: "NOTIFY",
              options: {
                channel: "Email",
                message: "This is the end, exit before it goes to 0."
              }
            }
          ]
        }
      ]
    }
  }
]
