// Predefined strategy templates
// Each strategy follows the same JSON structure as generated by Preview

export interface StrategyTemplate {
  id: string
  name: string
  description: string
  strategy: {
    strategyId: string
    strategyName: string
    symbols: string[]
    rules: {
      name: string
      conditions: {
        index: number
        type: string
        indicator1?: string
        timeframe1?: string
        indicator2?: string
        timeframe2?: string
        value?: number
      }[]
      actions: {
        index: number
        action: "BUY" | "SELL" | "NOTIFY"
        options: {
          amount?: number
          unit?: string
          channel?: string
          message?: string
        }
      }[]
    }[]
  }
}

export const predefinedStrategies: StrategyTemplate[] = [
  {
    id: "1",
    name: "Buy the Dip!",
    description: "Buy ETH and BTC when price drops at least 1% in 24 hours",
    strategy: {
      strategyId: "0391b0b0-01d8-4843-960a-e045052d7096",
      strategyName: "Buy when price drops",
      symbols: ["BTC/USD", "ETH/USD"],
      rules: [
        {
          name: "Buy the Dip",
          conditions: [
            {
              index: 0,
              type: "decreased-by",
              indicator1: "Price",
              timeframe1: "24h",
              value: 1,
            },
          ],
          actions: [
            {
              index: 0,
              action: "BUY",
              options: {
                amount: 25,
                unit: "USD",
              },
            },
          ],
        },
      ],
    },
  },
  {
    id: "2",
    name: "Buy HIGH, Sell LOW",
    description: "The best trading strategy,trust me bro.",
    strategy: {
      strategyId: "c7807204-2132-43ef-a23c-76d8d557dc7f",
      strategyName: "Buy High sell low",
      symbols: [
        "BTC/USD",
        "DOGE/USD",
        "SOL/USD"
      ],
      rules: [
        {
          name: "Buy High",
          conditions: [
            {
              index: 0,
              type: "increased-by",
              indicator1: "Price",
              timeframe1: "6h",
              value: 5
            }
          ],
          actions: [
            {
              index: 0,
              action: "BUY",
              options: {
                amount: 100,
                unit: "%"
              }
            },
            {
              index: 1,
              action: "NOTIFY",
              options: {
                channel: "Email",
                message: "Sure its gona go up!"
              }
            }
          ]
        },
        {
          name: "Sell Low",
          conditions: [
            {
              index: 0,
              type: "decreased-by",
              indicator1: "Price",
              timeframe1: "4h",
              value: 5
            }
          ],
          actions: [
            {
              index: 0,
              action: "SELL",
              options: {
                amount: 100,
                unit: "%"
              }
            },
            {
              index: 1,
              action: "NOTIFY",
              options: {
                channel: "Email",
                message: "This is the end, exit before it goes to 0."
              }
            }
          ]
        }
      ]
    }
  }
]
