// Predefined strategy templates

import { PredefinedStrategyTemplate } from "@palabola86/trade-strategy-builder";

// Each strategy follows the same JSON structure as generated by Preview
export const predefinedStrategies: PredefinedStrategyTemplate[] = [
  {
    id: "1",
    name: "Buy the Dip!",
    description: "Buy ETH and BTC when price drops at least 1% in 24 hours",
    strategy: {
      strategyName: "Buy the Dip",
      symbols: [
        "BTC/USD",
        "ETH/USD"
      ],
      executionOptions: {
        runIntervalMinutes: 60,
        maximumExecuteCount: 10,
        intervalBetweenExecutionsMinutes: 60,
        maximumOpenPositions: 1
      },
      rules: [
        {
          name: "Buy the Dip",
          conditions: [
            {
              index: 0,
              type: "decreased-by",
              options: {
                indicator1: "Price",
                timeframe1: "24h",
                value: 5
              }
            }
          ],
          actions: [
            {
              index: 0,
              action: "buy",
              options: {
                amount: 25,
                unit: "USD",
                takeProfit: 10,
                trailingStop: 5
              }
            }
          ]
        }
      ]
    }
  },
  {
    id: "2",
    name: "Buy HIGH, Sell LOW",
    description: "The best trading strategy,trust me bro.",
    strategy: {
      strategyName: "Buy High sell low",
      symbols: [
        "BTC/USD",
        "DOGE/USD",
        "SOL/USD"
      ],
      executionOptions: {
        runIntervalMinutes: 60,
        maximumExecuteCount: 100,
        intervalBetweenExecutionsMinutes: 15,
        maximumOpenPositions: 10
      },
      rules: [
        {
          name: "Buy High",
          conditions: [
            {
              index: 0,
              type: "increased-by",
              options: {
                indicator1: "Price",
                timeframe1: "4h",
                value: 1
              }
            }
          ],
          actions: [
            {
              index: 0,
              action: "buy",
              options: {
                amount: 100,
                unit: "%"
              }
            },
            {
              index: 1,
              action: "notify-me",
              options: {
                channel: "Email",
                message: "Sure its gona go up!"
              }
            }
          ]
        },
        {
          name: "Sell Low",
          conditions: [
            {
              index: 0,
              type: "decreased-by",
              options: {
                indicator1: "Price",
                timeframe1: "4h",
                value: 1
              }
            }
          ],
          actions: [
            {
              index: 0,
              action: "sell",
              options: {
                amount: 100,
                unit: "%"
              }
            },
            {
              index: 1,
              action: "notify-me",
              options: {
                channel: "Email",
                message: "This is the end, exit before it goes to 0."
              }
            }
          ]
        }
      ]
    }
  },
  {
    id: "3",
    name: "Complex Multi-Indicator Strategy",
    description: "A strategy that combines multiple indicators to make buy and sell decisions.",
    strategy: {
      strategyName: "Complex Multi-Indicator Strategy",
      symbols: [
        "BTC/USD",
        "ETH/USD",
        "SOL/USD"
      ],
      executionOptions: {
        runIntervalMinutes: 240,
        maximumExecuteCount: 200,
        intervalBetweenExecutionsMinutes: 240,
        maximumOpenPositions: 3
      },
      rules: [
        {
          name: "Buy on Bullish Signals",
          conditions: [
            {
              index: 0,
              type: "crossing-above",
              options: {
                indicator1: "EMA(20)",
                timeframe1: "4h",
                indicator2: "EMA(50)",
                timeframe2: "4h"
              }
            },
            {
              index: 1,
              type: "greater-than",
              options: {
                indicator1: "RSI(14)",
                timeframe1: "4h",
                indicator2: "Value",
                value: 40
              }
            }
          ],
          actions: [
            {
              index: 0,
              action: "buy",
              options: {
                amount: 50,
                unit: "USD",
                stopLoss: 2,
                takeProfit: 5
              }
            }
          ]
        },
        {
          name: "Sell on Bearish Signals",
          conditions: [
            {
              index: 0,
              type: "crossing-below",
              options: {
                indicator1: "EMA(20)",
                timeframe1: "4h",
                indicator2: "EMA(50)",
                timeframe2: "4h"
              }
            },
            {
              index: 1,
              type: "lower-than",
              options: {
                indicator1: "RSI(14)",
                timeframe1: "4h",
                indicator2: "Value",
                value: 60
              }
            }
          ],
          actions: [
            {
              index: 0,
              action: "sell",
              options: {
                amount: 100,
                unit: "%",
                stopLoss: 2,
                takeProfit: 5
              }
            }
          ]
        },
        {
          name: "Emergency Sell on Overbought",
          conditions: [
            {
              index: 0,
              type: "greater-than",
              options: {
                indicator1: "RSI(7)",
                timeframe1: "1h",
                indicator2: "Value",
                value: 80
              }
            }
          ],
          actions: [
            {
              index: 0,
              action: "sell",
              options: {
                amount: 100,
                unit: "%",
                stopLoss: 1,
                takeProfit: 3
              }
            }
          ]
        }
      ]
    }
  }
]
