// Predefined strategy templates

import { PredefinedStrategyTemplate } from "@palabola86/trade-strategy-builder";

// Each strategy follows the same JSON structure as generated by Preview
export const predefinedStrategies: PredefinedStrategyTemplate[] = [
  {
    id: "1",
    name: "Buy the Dip!",
    description: "Buy ETH and BTC when price drops at least 1% in 24 hours",
    strategy: {
  strategyId: "5b85b5c1-02cb-4156-98c8-d0e85622ad04",
  strategyName: "Buy the Dip",
  symbols: [
    "BTC/USD",
    "ETH/USD"
  ],
  executionOptions: {
    runIntervalMinutes: 60,
    maximumExecuteCount: 10,
    intervalBetweenExecutionsMinutes: 60,
    maximumOpenPositions: 1
  },
  rules: [
    {
      name: "Buy the Dip",
      conditions: [
        {
          index: 0,
          type: "decreased-by",
          options: {
            indicator1: "Price",
            timeframe1: "24h",
            value: 5
          }
        }
      ],
      actions: [
        {
          index: 0,
          action: "buy",
          options: {
            amount: 25,
            unit: "USD",
            takeProfit: 10,
            trailingStop: 5
          }
        }
      ]
    }
  ]
}
  },
  {
    id: "2",
    name: "Buy HIGH, Sell LOW",
    description: "The best trading strategy,trust me bro.",
    strategy: {
      strategyId: "c7807204-2132-43ef-a23c-76d8d557dc7f",
      strategyName: "Buy High sell low",
      symbols: [
        "BTC/USD",
        "DOGE/USD",
        "SOL/USD"
      ],
      executionOptions: {
        runIntervalMinutes: 15,
        maximumExecuteCount: 100,
        intervalBetweenExecutionsMinutes: 15,
        maximumOpenPositions: 10
      },
      rules: [
        {
          name: "Buy High",
          conditions: [
            {
              index: 0,
              type: "increased-by",
              options: {
                indicator1: "Price",
                timeframe1: "4h",
                value: 5
              }
            }
          ],
          actions: [
            {
              index: 0,
              action: "buy",
              options: {
                amount: 100,
                unit: "%"
              }
            },
            {
              index: 1,
              action: "notify-me",
              options: {
                channel: "Email",
                message: "Sure its gona go up!"
              }
            }
          ]
        },
        {
          name: "Sell Low",
          conditions: [
            {
              index: 0,
              type: "decreased-by",
              options: {
                indicator1: "Price",
                timeframe1: "4h",
                value: 5
              }
            }
          ],
          actions: [
            {
              index: 0,
              action: "sell",
              options: {
                amount: 100,
                unit: "%"
              }
            },
            {
              index: 1,
              action: "notify-me",
              options: {
                channel: "Email",
                message: "This is the end, exit before it goes to 0."
              }
            }
          ]
        }
      ]
    }
  }
]
